[build]
  functions = "netlify/functions"
  publish = "."

[[plugins]]
  package = "@netlify/plugin-scheduled-functions"

[[scheduled_functions]]
  function = "keepalive"
  cron = "*/5 * * * *" # every 5 minutes
