[build]
  publish = "."
  functions = "netlify/functions"

[[functions]]
  node_bundle = true  # Optional but recommended

[[functions.schedule]]
  cron = "*/5 * * * *"  # every 5 minutes
  function = "keepalive"